#!/bin/env python3
from argparse import ArgumentParser

from scitsifreine import TmuxSession


def main():
    arg_parser = ArgumentParser(prog='scitsi',
                                description='Helper script for creating multiple ssh sessions using tmux',
                                epilog='See more details at: https://docs.tmux.org')
    arg_parser.add_argument('hosts', metavar='hosts', type=str, nargs='+', help='a list of hosts to connect to')
    args = arg_parser.parse_args()
    TmuxSession(hosts=args.hosts)


if __name__ == '__main__':
    main()
