#!/usr/bin/env python3
from argparse import ArgumentParser

from scitsifreine import TmuxSession


def main():
    arg_parser = ArgumentParser(prog='scitsi',
                                description='helper script for creating multiple ssh sessions using tmux',
                                epilog='see more details at: https://docs.tmux.org')
    arg_parser.add_argument('hosts', metavar='hosts', type=str, nargs='+', help='a list of hosts to connect to')
    arg_parser.add_argument('-c', '--close-on-exit', action='store_true',
                            help='terminate the tmux session when its closed or move to the background (detached)')
    args = arg_parser.parse_args()
    TmuxSession(hosts=args.hosts, close_on_exit=args.close_on_exit)


if __name__ == '__main__':
    main()
